# Generated by Django 5.0.6 on 2024-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("user_name", models.TextField()),
                ("password", models.CharField(max_length=3000)),
                ("email", models.EmailField(max_length=250)),
            ],
        ),
    ]
